# Generated by Django 5.0.6 on 2024-06-05 09:03

import django.db.models.deletion
import ui.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('sent_id', models.CharField(max_length=30)),
                ('text', models.TextField()),
                ('comments', models.JSONField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Treebank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('language', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TreebankFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=ui.models.user_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='ExtendUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferences', models.JSONField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annotator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.sentence')),
            ],
        ),
        migrations.AddField(
            model_name='sentence',
            name='treebank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.treebank'),
        ),
        migrations.CreateModel(
            name='Word_Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_f', models.CharField(max_length=10)),
                ('form', models.CharField(max_length=100)),
                ('lemma', models.CharField(max_length=100)),
                ('upos', models.CharField(max_length=100)),
                ('xpos', models.CharField(max_length=100)),
                ('feats', models.CharField(max_length=500)),
                ('head', models.CharField(max_length=100)),
                ('deprel', models.CharField(max_length=100)),
                ('deps', models.CharField(max_length=100)),
                ('misc', models.CharField(max_length=200)),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.annotation')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='sentence',
            unique_together={('sent_id', 'text', 'treebank')},
        ),
    ]
